### ISSUE TITLE
Please add a screen shot to the readme

### ISSUE THREAD

**Issue by unixorn** [redxtech/zshred#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by redxtech** [comment]
Thanks for the interest!

There should be a screenshot there now. Not sure why it wasn't showing up before, thought I had one there.

**Comment by unixorn** [comment]
Thanks, adding in https://github.com/unixorn/awesome-zsh-plugins/pull/808
